name       : jtreg
version    : 6.2
release    : 1
source     :
    - https://github.com/openjdk/jtreg/archive/refs/tags/jtreg-6.2+1.tar.gz : d2a4ef1b7d3cf748ea116fcc67c1f60418eb790884b5c3395bd2a6d6bba1d728
license    : GPL-2.0-only WITH Classpath-exception-2.0
summary    : Test harness for testing the JDK
description: |
    Test harness for testing the JDK
component  : programming.java
networking : yes
builddeps  :
    - openjdk-11
environment: |
    export JAVA_HOME=/usr/lib64/openjdk-11
    export PATH=$JAVA_HOME/bin:$PATH

    unset LD_PRELOAD
setup      : |
    # Why does it hardcode these paths? Who knows
    sed -i "s|/usr/bin/sort|/bin/sort|" make/Defs.gmk
    sed -i "s|/usr/bin/touch|/bin/touch|" make/Defs.gmk
build      : |
    bash make/build.sh --jdk $JAVA_HOME
install    : |
    install -dm00755 $installdir/usr/share/
    cp -r --preserve=mode,timestamps build/images/jtreg $installdir/usr/share/

    install -dm00755 $installdir/usr/bin/
    ln -s /usr/share/jtreg/bin/jtdiff $installdir/usr/bin/jtdiff
    ln -s /usr/share/jtreg/bin/jtreg $installdir/usr/bin/jtreg
